FROM ntb/debian:stretch
MAINTAINER jinjiao@tencent.com

# use tencent apt sources
RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
        echo "deb [trusted=yes] http://mirrors.cloud.tencent.com/debian stretch main non-free contrib" >> /etc/apt/sources.list && \
        echo "deb [trusted=yes] http://mirrors.cloud.tencent.com/debian stretch-updates main non-free contrib"  >> /etc/apt/sources.list && \
        echo "deb [trusted=yes] http://mirrors.cloud.tencent.com/debian-security/ stretch/updates main contrib non-free"  >> /etc/apt/sources.list && \
        echo "deb [trusted=yes] http://mirrors.cloud.tencent.com/debian stretch-backports main contrib non-free" >> /etc/apt/sources.list

## Make apt-get non-interactive
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Shanghai

RUN mkdir -p /root/.pip/
COPY ["pip.conf",  "/root/.pip/"]

# install tool
RUN apt-get update && apt-get install -y \
	lrzsz \
	sudo \
	vim \
# install python
	python       \
	python3      \
	python-pip   \
	python3-pip  \
        rsyslog      \
        supervisor   \
        libunwind8   \
        libgoogle-perftools4 \
# Install dependencies of supervisor
        python-pkg-resources \
        python-meld3 \
# Install tools
        inetutils-ping \
        net-tools \
        procps \
        kmod \
        wget \
        tcpdump \
# Install dpdk dependencies
        libnuma-dev \
        libevent-dev \
        libjudy-dev \
        libpcap-dev \
# Install gdb
        gdb \
        strace \
# install bsp dep
        libusb-1.0-0-dev \
        libpsl-dev \
        libpsl5 \
        libssh2-1 \
        librtmp1 \
        libidn2-0 \
        libnghttp2-14 \ 
        libcurl3-gnutls \
#install alarm and monitor
        libssl-dev \
        libcurl4-gnutls-dev \
        libjsoncpp-dev \
        libczmq-dev \
#install perf
        linux-tools \
#install libnl
        libnl-3-dev \
        libnl-genl-3-dev \
        libnl-route-3-dev

RUN pip install  -U --upgrade pip
RUN pip install  -U grpcio==1.34.1 \
		        grpcio-tools==1.34.1 \
                requests \
                click \
                protobuf==3.17.0 \
                tabulate \
                pyzmq

RUN pip3 install -U requests \
                plotext==4.2.0 \
                click \
                tabulate

RUN export REPO_USER=g_ntb_public \
    && export REPO_TOKEN=f9db1b96790711ecbf506225058ed3dc \
    && export REPO_URL=https://mirrors.tencent.com/repository/generic/ntb/deb/ \
    && wget --user $REPO_USER --password $REPO_TOKEN $REPO_URL/libdpdk-dev_20.11.3-1_amd64.deb \
    && dpkg -i ./libdpdk-dev_20.11.3-1_amd64.deb && rm libdpdk-dev_20.11.3-1_amd64.deb && ldconfig

RUN mkdir -p /etc/supervisor /var/log/supervisor

COPY ["rsyslog.conf", "/etc/rsyslog.conf"]
COPY ["rsyslog.d/*", "/etc/rsyslog.d/"]
COPY ["start.sh", "/usr/bin/"]
COPY ["ntb.sh", "/usr/bin/"]
COPY ["confpreprocess", "/usr/bin/"]
COPY ["supervisord.conf", "/etc/supervisor/conf.d/"]
COPY ["supervisor-proc-exit-listener", "/usr/bin"]
COPY ["critical_processes", "/etc/supervisor"]
COPY ["zlog-cfg",  "/opt/file/install/share/bfsys/"]
COPY ["bash.bashrc", "/etc/bash.bashrc"]

RUN export SDE=/opt/file \
        && export SDE_INSTALL=/opt/file/install \
        && export PATH=$SDE_INSTALL/bin:$PATH \
        && export USER=root \
        && echo "export SDE=/opt/file" >> ~/.bashrc \
        && echo "export SDE_INSTALL=$SDE/install" >> ~/.bashrc \
        && echo "export PATH=$PATH" >> ~/.bashrc \
        && echo "export LANG=C.UTF-8" >> ~/.bashrc \
        && echo "export LC_ALL=C.UTF-8" >> ~/.bashrc \
        && echo "export USER=root" >> ~/.bashrc \
        && echo "$SDE_INSTALL/lib/" >> /etc/ld.so.conf.d/ntb.conf \
        && ldconfig

WORKDIR "/opt/file/"
COPY ["*.deb", "ntb_cli-*.whl",  "/opt/file/"]
RUN dpkg -i *deb && rm *deb && ldconfig && confpreprocess ./install/share/p4/targets/tofino/ntb.conf

RUN  if test -e /opt/file/ntb_cli-*.whl; then pip install /opt/file/ntb_cli-*.whl; rm /opt/file/ntb_cli*.whl; fi

RUN apt-get clean -y; apt-get autoclean -y; apt-get autoremove -y

ENTRYPOINT ["/usr/bin/supervisord"]
